[package]
name = "one-billion-row-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.5.0"
ahash = "0.8"
rand = "0.8"
rand_distr = "0.4"

[[bin]]
name = "create-sample"
path = "src/create-sample.rs"